---

- name: "Config | Copy initialization script"
  become: yes
  become_user: root
  template:
    src: ../templates/debian.j2
    dest: /etc/init.d/teamcity
    owner: root
    group: root
    mode: 0755

- name: "Config | Install intialization script"
  become: yes
  become_user: root
  shell: update-rc.d teamcity defaults